### ISSUE TITLE
Valid clj keyword benchmark names are munged to invalid Java method names

### ISSUE THREAD

**Issue by KingMob** [jgpc42/jmh-clojure#10]
Dots are allowed in clj keywords, but if I name a benchmark something like `:manifold.speederino.bus-test`, jmh-clojure generates a `.class` with a method name like `_000_manifold.speederino.bus_test`, which is invalid in Java. I haven't checked, but I'll bet other valid keyword chars are munged incorrectly, too.

**Comment by jgpc42** [comment]
I see Clojure's built-in `munge` doesn't handle dot. Considering most other valid keyword characters like `🐦` are also left intact by it, the only way that would allow for arbitrary (Clojure) names for Java identifiers would be something like:

```clojure
(defn identifier-name [s]
  (clojure.string/replace
   (-> s name munge)
   #"^\d|[^\p{L}\p{N}_]" ;; etc.
   (fn [m]
     (->> (.codePointAt m 0)
          (Character/toChars)
          (map (comp (partial format "_u%04x") int))
          (apply str)))))

(identifier-name :manifold.speederino.bus-test)
;; => "manifold_u002espeederino_u002ebus_test"

(identifier-name :42🐦fredπ)
;; => "_u00342_ud83d_udc26fredπ"
```

Although, with that, it would sometimes make it hard to correlate generated names back to the original Clojure. Alternatively, I could just raise an error.

**Comment by KingMob** [comment]
Well, I can say that personally, I would prefer names that are correlatable back, since I'm working on something where I won't always be able to control the original names.

**Comment by KingMob** [comment]
(Sorry for the delay btw, I'm on vacation.)

**Comment by jgpc42** [comment]
> (Sorry for the delay btw, I'm on vacation.)

No problem, and thanks for the additional input.

I was curious as to what Clojure does when it comes to generating class and method names. For example, in a test project:

```sh
$ mkdir -p classes demo
$ echo '{:paths ["." "classes"]}' > deps.edn
$ clj
```

```clj
(in-ns 'user)
(System/getProperty "java.version")
;; => "14.0.2"
*clojure-version*
;; => {:major 1, :minor 10, :incremental 3, :qualifier nil}

(munge '&)
;; => _AMPERSAND_
```

Somewhat surprisingly, Clojure can generate classes with names that are invalid according to `javac`. For example:

```clj
(spit "./demo/&.clj" (pr-str '(do (ns demo.& (:gen-class))
                                  (defn -main [& _] (prn :wow)))))
(compile 'demo.&)
;; => demo.&

(import [demo &])

(&.)
;; => #object[demo.& 0x178270b2 "demo.&@178270b2"]
```

If we look with `javap`, we see the same name:

```sh
$ javap 'classes/demo/&.class' | head -n1
public class demo.& {
```

But if we try to create a class with the same name with `javac` it (expectedly) fails:

```sh
$ echo 'public class & {}' > 'demo/&.java'
$ javac 'demo/&.java'
```

```
demo/&.java:1: error: <identifier> expected
public class & {}
            ^
1 error
```

But perhaps even more surprising, while `javac` can't create them, `java` can still run the ones generated by Clojure:

```sh
$ java -cp "$(clj -Spath)" 'demo.&'
:wow
```

However, while it can generate ostensibly invalid class names, it won't allow the same for methods.

```clj
(spit "./demo/test2.clj"
      (pr-str '(do (ns demo.test2 (:gen-class :methods [[& [] String]]))
                   (defn -& [] "???")
                   (defn -main [& _] (prn (-&))))))
(compile 'demo.test2)
;; Syntax error macroexpanding clojure.core/gen-class at (demo/test2.clj:1:5).
;; Not a valid method name: &
```

But, of course, it works fine from Clojure:

```clj
(require 'demo.test2 :reload)
(demo.test2/-main)
;; "???"
```

---

Anyway, I hope you don't mind the small brain dump.

So, I think raising an error if the munged name is still an invalid Java method name is the right course of action. This will be less restrictive than [Clojure's `gen-class`][ref], which doesn't allow even munge-able characters like `-`, but it still will disallow dot as a valid character for benchmark names.

If you don't have any more input or objections, I'll likely get to enforcing this in the code some time next week.


[ref]: https://github.com/clojure/clojure/blob/38705b4/src/clj/clojure/genclass.clj#L114

**Comment by jgpc42** [comment]
Added in ca59c72.

**Comment by KingMob** [comment]
Sounds good to me. Thanks for fixing it.
