### ISSUE TITLE
Best way to benchmark a variable number of arguments

### ISSUE THREAD

**Issue by bsless** [jgpc42/jmh-clojure#9]
Hello,
I'm benchmarking code I wrote which does some inlining at macro expansion time.
A simple example would be `get-in`
My inlining code runs if the keys can be expanded at compile time, i.e.
```clojure
(get-in m ks) ;; baseline
(inline/get-in m ks) ;; will run like regular get-in
(inline/get-in m [k1 k2 k3]) ;; will inline
```
I want to run benchmarks which will scan over the keys depth. To bench `clojure.core/get-in` I just need:
```
{:name :core/get-in :fn clojure.core/get-in :args [:state/map :state/ks]}
```
However, to get the benefits of inlining, I need to build some wrapper around my code:
```clojure
(defn inline-get-in
  ([m k1] (inline/get-in m [k1]))
  ([m k1 k2] (inline/get-in m [k1 k2]))
  ([m k1 k2 k3] (inline/get-in m [k1 k2 k3]))
  ([m k1 k2 k3 k4] (inline/get-in m [k1 k2 k3 k4])))
```
I don't want to use args like `[m [k1 k2 ,,,]]` as it will incur the destructuring overhead at run time.
Another option is unrolling individual keys to states, but then I will need to duplicate benchmarks.

Any tips or directions would be very welcome
Thanks!

**Comment by bsless** [comment]
Managed to work something out by using partial application:
```clojure
(defn inline-get-in-fn
  [[k1 k2 k3 k4 :as ks]]
  (case (count ks)
    1 (fn [m] (inline/get-in m [k1]))
    2 (fn [m] (inline/get-in m [k1 k2]))
    3 (fn [m] (inline/get-in m [k1 k2 k3]))
    4 (fn [m] (inline/get-in m [k1 k2 k3 k4]))))

(defn invoke
  ([f] (f))
  ([f a] (f a))
  ([f a b] (f a b)))
```
Then it works with the following config:
```clojure
{:benchmarks
 [{:name :core/get-in :fn clojure.core/get-in :args [:state/map :state/ks]}
  {:name :inline/get-in :fn clj-fast.bench/invoke :args [:state/inline-get-in-fn :state/map]}]
 :states
 {:map-size {:fn (fn [x] (int (Math/pow 10 x))) :args [:param/log-map-size]}
  :map {:fn clj-fast.bench/mrand-nested-map :args [:param/type :state/map-size :param/keys-depth]}
  :inline-get-in-fn {:fn clj-fast.bench/inline-get-in-fn :args [:state/ks]}
  :ks {:fn clj-fast.bench/randpath :args [:state/map]}}
 :params
 {:log-map-size [0 #_#_1 2]
  :keys-depth [1 2 #_3 #_4]
  :type :keyword?}}
```

**Comment by jgpc42** [comment]
It's an interesting problem. Another instance of macros causing issues. Anyway, from what I can tell, something like that, or a variation of that, looks like the right solution. ~~What also may work is bypassing the macro and just benchmarking the resulting [`lens/get`](https://github.com/bsless/clj-fast/blob/a58db46/src/clj_fast/inline.clj#L156) invocation directly, but I don't know if that is possible in your case.~~

Thanks for bringing this to my attention.

**Edit:** Nevermind, I see that `lens/get` is just a code transformer.

**Comment by bsless** [comment]
Thank you for taking the time to look at it anyway.
The problem with macros is that once you start with them, they're hard to get rid of :)
You can take a peek at the branch I started working on to see the approach I ended up taking
see here:
https://github.com/bsless/clj-fast/blob/jmh/extra/clj-fast.jmh/src/clj_fast/bench.clj#L168
https://github.com/bsless/clj-fast/blob/jmh/extra/clj-fast.jmh/jmh.edn

In the end, just dancing around delayed application, as always

I also feel I must commend how you went above and beyond and looked through the implementation. Thank you!

**Comment by jgpc42** [comment]
No problem - I always enjoy checking out how others are using this library, and I like your approach here quite a bit. One of the pain points I've experienced developing this library has always been the mismatch of the static nature of Java (for which JMH was designed) vs. the dynamic nature of Clojure and you've worked around this quite nicely from what I see here.

Nice talking to you, and thank you for your kind words!
